---
- name: kubeconfig | Download kubectl 
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v{{ kubernetes_version }}/bin/linux/amd64/kubectl
    dest: /usr/bin/kubectl
    mode: 0755 


- name: kubeconfig | Create dir
  file:
    path: "{{ k8s_config_dir }}"
    state: directory


- name: auth-config | Generate token for kubelet
  include: auth-config__token.yml
  when: deploy_token
  tags:
    - token


- name: kubeconfig | create kubeconfig bootstrap
  include: auth-config__bootstrap.yml
  when: deploy_kubeconfig
  tags:
    - kubeconfig


- name: kubeconfig | create kubeconfig kube-proxy
  include: auth-config__kube-proxy.yml
  when: deploy_kubeconfig
  tags:
    - kubeconfig
