---
- name: kubeconfig | set-cluster
  shell: >
    kubectl config set-cluster kubernetes-cluster 
    --certificate-authority={{ ssl_dir }}/ca.pem
    --embed-certs=true 
    --server=https://{{ api_domain }} 
    --kubeconfig={{ k8s_config_dir }}/kube-proxy.kubeconfig

- name: kubeconfig | set-credentials
  shell: >
    kubectl config set-credentials kube-proxy 
    --client-certificate={{ ssl_dir }}/kube-proxy.pem 
    --client-key={{ ssl_dir }}/kube-proxy-key.pem 
    --embed-certs=true 
    --kubeconfig={{ k8s_config_dir }}/kube-proxy.kubeconfig


- name: kubeconfig | set-context
  shell: >
    kubectl config set-context default
    --cluster=kubernetes-cluster
    --user=kube-proxy 
    --kubeconfig={{ k8s_config_dir }}/kube-proxy.kubeconfig


- name: kubeconfig | use-context
  shell: >
    kubectl config use-context default 
    --kubeconfig={{ k8s_config_dir }}/kube-proxy.kubeconfig 
