---
- name: kubernetes | General roles
  hosts: all
  remote_user: ansible
  environment: "{{ proxy_env }}"
  roles:
    - common
    - firewalld
    - ntp-client
  tags:
    - k8s-common
  

- name: kubernetes | Create main certificates
  hosts: main_host
  remote_user: ansible
  environment: "{{ proxy_env }}"
  roles:
    - cert-create
  tags:
    - k8s-cert-create


- name: kubernetes | Distribuite SSL certificates master, etcd
  hosts: [ main_host, master, etcd, node ]
  remote_user: ansible
  environment: "{{ proxy_env }}"
  roles:
    - cert-dist
  tags:
    - k8s-cert-dist


- name: Kubernetes | etcd
  hosts: etcd
  remote_user: ansible
  environment: "{{ proxy_env }}"
  roles:
    - etcd
  tags:
    - k8s-etcd


- name: Kubernetes | master
  hosts: master
  remote_user: ansible
  environment: "{{ proxy_env }}"
  roles:
    - master
  tags:
    - k8s-master


- name: kubernetes | Load Balancer
  hosts: lb
  remote_user: ansible
  environment: "{{ proxy_env }}"
  roles:
    - keepalived
    - nginx
  tags:
    - k8s-lb


- name: kubernetes | Node
  hosts: node
  remote_user: ansible
  environment: "{{ proxy_env }}"
  roles:
    - cert-node
    - kubeconfig
    - docker
    - node
  tags:
    - k8s-node


- name: kubernetes | Network
  hosts: node
  remote_user: ansible
  environment: "{{ proxy_env }}"
  roles:
    - network
  tags:
    - k8s-network


- name: kubernetes | Addons
  hosts: main_host
  remote_user: ansible
  environment: "{{ proxy_env }}"
  roles:
    - addons
  tags:
    - k8s-addons
