--- 
- name: dist | etcd ssl cert
  copy: 
    src: /tmp/{{ item }}
    dest: /etc/etcd/
  with_items:
    - ca.pem
    - kubernetes.pem
    - kubernetes-key.pem
  when: "'etcd' in group_names"


- name: dist | master ssl cert
  copy:
    src: /tmp/{{ item }}
    dest: /var/lib/kubernetes/
  with_items:
    - ca.pem 
    - ca-key.pem 
    - kubernetes-key.pem 
    - kubernetes.pem
  when: "'master' in group_names"


- name: dist | node ssl cert
  copy:
    src: /tmp/{{ item }}
    dest: /var/lib/kubernetes/
  with_items:
    - ca.pem
    - kube-proxy.pem
    - kube-proxy-key.pem
    - node.pem
    - node-key.pem
  when: "'node' in group_names"


- name: dist | master token
  copy:
    src: /tmp/token.csv
    dest: /var/lib/kubernetes/
  when: "'master' in group_names"


- name: dist | node bootstrap.kubeconfig
  copy:
    src: /tmp/bootstrap.kubeconfig
    dest: /var/lib/kubelet/
  when: "'node' in group_names"


- name: dist | node kube-proxy.kubeconfig
  copy:
    src: /tmp/kube-proxy.kubeconfig
    dest: /var/lib/kube-proxy/
  when: "'node' in group_names"  
