---
- name: dist-keys | create directories
  include: create_dir.yml


- name: dist-keys | Fetch keys
  include: fetch.yml
  tags:
    - fetch_keys


- name: dist-keys | Distribuite keys
  include: dist.yml
  tags:
    - dist_keys


- name: dist-keys | Reload Services
  include: reload_services.yml 
  when: deploy_certificates
  tags:
    - reload_services
    
  
