---
- name: reload_services | etcd
  systemd:
    name: etcd 
    state: restarted
  when: 
    - "'etcd' in group_names"
    - not deploy_etcd

 
- name: reload_services | master services
  systemd:
    name: "{{ item }}"
    state: restarted
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
  when: 
    - "'master' in group_names"
    - not deploy_master
