---
- name: kube-backup | Install ark
  include: ark.yml
  tags:
    - kube-backup


- name: kube-backup | Deploy kubernetes yaml's
  include: deploy.yml
  when: deploy_ark
  tags:
    - kube-backup

