---
## KUBERNETES
#-------------
kubernetes_version: 1.7.5
api_public_ip: "{{ lb_ip_apik8s }}"
api_private_ip: 10.254.0.1
cluster_dns: 10.254.0.10
api_domain: apik8s-{{ env_site }}.iplanet.work
cluster_name: unicred.local
cluster_cidr: 172.18.0.0/16
kubernetes_setup_dir: /opt/kubernetes
cert_expiry_time: 87600h

## KUBERNETES_TOKENS
# ------------------
# To create new token. `head -c 16 /dev/urandom | od -An -t x`
token_kubelet_bootstrap: ea0da8d7d09fa787cfeee32dcf1ed565


## DEPLOY
#---------- 
# To init the installation all the vars deploy_*  should set to "true"
#
deploy_certificates: false
deploy_token: false
deploy_kubeconfig: false
deploy_etcd: false
deploy_cni: false
deploy_node: false
deploy_master: false
deploy_docker: false
deploy_addons: false
