---
## KUBERNETES
## ----------

kubernetes_version: 1.7.5
cni_version: 0799f5732f2a11b329d9e3d51b9c8f2e3759f2ff

api_public_ip: "{{ lb_ip_apik8s }}"
api_private_ip: 10.254.0.1
cluster_dns: 10.254.0.10
api_domain: apik8s-{{ env_site }}.iplanet.work
cluster_name: iplanet.local
cluster_cidr: 172.18.0.0/16
kubernetes_setup_dir: /opt/kubernetes

network_plugin: cni
calicoctl_version: 1.5.0

## SSL
cert_expiry_time: 87600h


## KUBERNETES_TOKENS (to create new token, execute `head -c 16 /dev/urandom | od -An -t x`)
## -----------------

token_kubelet_bootstrap: ea0da8d7d09fa787cfeee32dcf1ed565


## DEPLOY (to init the installation all the vars deploy_*  should set to "true")
## ------

deploy_certificates: false
deploy_kubeconfig: false
deploy_etcd: false
deploy_network: false
deploy_cni: false
deploy_node: false
deploy_master: false
deploy_docker: false
deploy_addons: false
