# Variables for role keepalived
#
keepalived_auth_pass: "passwd"
keepalived_role: "MASTER"
keepalived_router_id: "52"
keepalived_shared_iface: "eth0"
keepalived_shared_ip: "192.168.1.1"
keepalived_check_process: "keepalived"
keepalived_priority: "100"
keepalived_backup_priority: "50"
