---
- name: kubenet | deploy
  include: kubenet.yml
  when:
    - deploy_network
    - network_plugin == "kubenet"


- name: calico | deploy calico network
  include: calico.yml
  when:
    - deploy_network
    - network_plugin == "cni"

