---
- name: cni | create dir
  file:
    path: /opt/cni
    state: directory 
  tags:
    - cni

- name: cni | download 
  unarchive:
    src: https://storage.googleapis.com/kubernetes-release/network-plugins/cni-amd64-0799f5732f2a11b329d9e3d51b9c8f2e3759f2ff.tar.gz
    dest: /opt/cni
    remote_src: yes
  when: deploy_cni
  tags:
    - cni

