---
- name: docker | download package
  unarchive:
    src: https://get.docker.com/builds/Linux/x86_64/docker-{{ docker_version }}.tgz
    dest: /opt
    remote_src: yes
  when: deploy_docker
  tags:
    - docker

- name: docker | copy binaries
  copy: 
    src: /opt/docker/{{ item }}
    dest: /usr/bin/{{ item }}
    remote_src: yes
    mode: 0755
  with_items:
    - docker
    - docker-containerd
    - docker-containerd-ctr
    - docker-containerd-shim
    - docker-proxy
    - docker-runc
    - dockerd
  notify: restart docker
  when: deploy_docker
  tags:
    - docker    


- name: docker | Copy service systemd 
  template: src=docker.service dest=/usr/lib/systemd/system/docker.service
  notify: 
    - reload systemd
    - restart docker
  tags:
    - docker


- name: docker | Start service
  systemd: name=docker state=started enabled=yes
  tags:
    - docker

- name: docker | Restart service
  systemd: name=docker state=restarted
  when: deploy_docker
  tags:
    - docker
