---
- name: node | install pre-req pacakges 
  yum: 
    name: "{{ item }}"
    state: present
  with_items:
    - conntrack-tools


- name: node | install binaries
  get_url:
    url: "{{ kubernetes_install_url }}/{{ item }}"
    dest: /usr/bin/
    mode: 0755
  with_items:
    - kubectl
    - kube-proxy
    - kubelet
  when: deploy_node


- name: node | setup service
  include: setup-service.yml


- name: node | start service
  include: start-service.yml


