---
- name: node | setup kubelet.service
  template:
    src: kubelet.service
    dest: /usr/lib/systemd/system/
  notify: 
    - reload systemd
    - restart kubelet


- name: node | setup kube-proxy.service
  template:
    src: kube-proxy.service
    dest: /usr/lib/systemd/system/
  notify:  
    - reload systemd
    - restart kube-proxy

