---
apiVersion: v1
kind: Service
metadata:
  namespace: heptio-ark
  name: minio
  labels:
    component: minio
spec:
  externalName: {{ backup_minio_host }}
  type: ExternalName
  selector:
    component: minio
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Secret
metadata:
  namespace: heptio-ark
  name: cloud-credentials
  labels:
    component: minio
stringData:
  cloud: |
    [default]
    aws_access_key_id = {{ backup_minio_access_key }}
    aws_secret_access_key = {{ backup_minio_secret_key }}

---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: heptio-ark
  name: minio-setup
  labels:
    component: minio
spec:
  template:
    metadata:
      name: minio-setup
    spec:
      restartPolicy: OnFailure
      volumes:
      - name: config
        emptyDir: {}
      containers:
      - name: mc
        image: minio/mc:latest
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - "mc --config-folder=/config config host add ark http://{{ backup_minio_host }} {{ backup_minio_access_key }} {{ backup_minio_secret_key }} && mc --config-folder=/config mb -p ark/ark"
        volumeMounts:
        - name: config
          mountPath: "/config"
