---
- name: createrole | binding kubelet
  shell: >
    kubectl create clusterrolebinding kubelet-bootstrap 
    --clusterrole=system:node-bootstrapper 
    --user=kubelet-bootstrap
  ignore_errors: true


- name: createrole | binding auto kubelet-binding
  shell: >
    kubectl create clusterrolebinding kubelet-node-binding 
    --clusterrole=system:node 
    --user=kubelet-bootstrap
  ignore_errors: true


- name: createrole | binding serviceaccounts-cluster-admin
  shell: >
    kubectl create clusterrolebinding serviceaccounts-cluster-admin
    --clusterrole=cluster-admin
    --group=system:serviceaccounts
  ignore_errors: true

