---
- name: master | install binaries
  get_url:
    url: "{{ kubernetes_install_url }}/{{ item }}"
    dest: /usr/bin/
    mode: 0755
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
    - kubectl
  when: deploy_master


- name: master | create dir
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /var/log/kubernetes
    - /var/lib/kubernetes
    - /var/run/kubernetes
