---
- name: master | install binaries kubernetes
  include: install.yml


- name: master | copying token.cvs
  include: token.yml


- name: master | setup services
  include: setup-service.yml


- name: master | start services
  include: start-service.yml


- name: master | pause 
  pause:
    seconds: 10
  when: deploy_master


- name: master | setup clusterrol
  include: clusterrole.yml
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  when: deploy_master
  tags:
    - clusterrole

- name: master | restart services
  include: restart-service.yml
  when: deploy_master
