---

- name: addons | taint nodes
  include: taint.yml
  when: deploy_addons
  tags:
    - taint

- name: addons | dns
  include: kube-dns.yml
  when: deploy_addons
  tags:
    - kube-dns


- name: addons | busybox
  include: busybox.yml
  when: deploy_addons
  tags:
    - busybox


- name: addons | heapster
  include: heapster.yml
  when: deploy_addons
  tags:
    - heapster


- name: addons | ingress
  include: ingress.yml
  when: deploy_addons
  tags:
    - ingress

- name: addons | dashboard
  include: dashboard.yml
  when: deploy_addons
  tags:
    - dashboard
