---
- name: kubeconfig | set-cluster
  shell: >
    kubectl config set-cluster kubernetes-cluster 
    --certificate-authority=/var/lib/kubernetes/ca.pem
    --embed-certs=true 
    --server=https://{{ api_domain }} 
    --kubeconfig=/var/lib/kube-proxy/kube-proxy.kubeconfig


- name: kubeconfig | set-credentials
  shell: >
    kubectl config set-credentials kube-proxy 
    --client-certificate=/var/lib/kubernetes/kube-proxy.pem 
    --client-key=/var/lib/kubernetes/kube-proxy-key.pem 
    --embed-certs=true 
    --kubeconfig=/var/lib/kube-proxy/kube-proxy.kubeconfig


- name: kubeconfig | set-context
  shell: >
    kubectl config set-context default
    --cluster=kubernetes-cluster
    --user=kube-proxy 
    --kubeconfig=/var/lib/kube-proxy/kube-proxy.kubeconfig


- name: kubeconfig | use-context
  shell: >
    kubectl config use-context default 
    --kubeconfig=/var/lib/kube-proxy/kube-proxy.kubeconfig 
